MODEL:
    NUM_CLASSES: 5
INPUT:
    IMAGE_SIZE: [300, 300]
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    MAX_ITER: 10000
    GAMMA: 0.1
    BATCH_SIZE: 32
    LR: 2e-4
OUTPUT_DIR: 'outputs/project'
DATASET_DIR: "/work/datasets"