MODEL:
    NUM_CLASSES: 5
#    BACKBONE:
#        NAME: 'resnet'
#        OUT_CHANNELS: [128, 256, 512, 128, 64, 64]
INPUT:
    PIXEL_STD: [0.003921569, 0.003921569, 0.003921569] # Set pixel std to 1/255 as VGG is pre-trained on images in range (roughly) [-127.5, 127.5]
    IMAGE_SIZE: [300, 300]
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    MAX_ITER: 15000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
    WEIGHT_DECAY: 1e-4
    OPTIM: "Adam"
OUTPUT_DIR: 'outputs/project'
DATASET_DIR: "/work/datasets"
#EVAL_STEP: 2000
#MODEL_SAVE_STEP: 2000