MODEL:
  NUM_CLASSES: 5
  BACKBONE:
    NAME: 'basic'
    PRETRAINED: False
    OUT_CHANNELS: [128, 256, 128, 128, 64, 64]
    INPUT_CHANNELS: 3
    BASIC: False
  PRIORS:
    MIN_SIZES: [[2, 2], [15, 15], [30, 30], [60, 60], [150, 150], [230, 230]]
    MAX_SIZES: [[15, 15], [30, 30], [60, 60], [150, 150], [230, 230], [300, 300]]
INPUT:
  IMAGE_SIZE: [300, 300]
DATASETS:
  TRAIN: ("rdd2020_train",)
  TEST: ("rdd2020_val", )
SOLVER:
  MAX_ITER: 15000
  GAMMA: 0.1
  BATCH_SIZE: 64
  LR: 1e-3
  WEIGHT_DECAY: 1e-4
  OPTIM: "Adam"
OUTPUT_DIR: 'outputs/rdd2020'
DATASET_DIR: "datasets"
