MODEL:
  NUM_CLASSES: 11
  BACKBONE:
    NAME: 'basic'
    PRETRAINED: False
    OUT_CHANNELS: [128, 256, 128, 128, 64, 64]
    INPUT_CHANNELS: 3
    BASIC: False
  PRIORS:
    MIN_SIZES: [[12, 12], [60, 60], [111, 111], [162, 162], [213, 213], [264, 264]]
INPUT:
  IMAGE_SIZE: [300, 300]
DATASETS:
  TRAIN: ("mnist_detection_train", "mnist_detection_val")
  TEST: ("mnist_detection_val", )
SOLVER:
  MAX_ITER: 15000
  GAMMA: 0.1
  BATCH_SIZE: 64
  LR: 1e-3
  WEIGHT_DECAY: 1e-4
  OPTIM: "Adam"
OUTPUT_DIR: 'outputs/basic'
DATASET_DIR: "datasets"
