MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'basic'
        PRETRAINED: False
        OUT_CHANNELS: [128, 256, 128, 128, 64, 64]
        INPUT_CHANNELS: 3
INPUT:
    IMAGE_SIZE: [300, 300]
DATASETS:
    TRAIN: ("tdt4265_train",)
    TEST: ("tdt4265_val", )
SOLVER:
    MAX_ITER: 10000
    GAMMA: 0.1
    BATCH_SIZE: 32
    LR: 2e-3
OUTPUT_DIR: 'outputs/project'
DATASET_DIR: "/work/datasets"
